### ISSUE TITLE
Errors on using map/single-view

### ISSUE THREAD

**Issue by bh-teufels** [joachimruhs/myttaddressmap#1]
Hello,

i placed the Plugins like in the extension manual

[2111] address
- [2119] ajax map 
- [2120] search (combined form and result)
- [2121] detail

My configuration:
```
plugin.tx_myttaddressmap {
    settings {

    	resultPageId = 2120
    	detailsPageId = 2121
    	singleViewUid = 2121

	googleBrowserApiKey = ***
	googleServerApiKey = ***
	}
}
```

but if i open the Page "ajax map" i get the JS Error 
`POST http://mydomain.de/address/index.php?eIDx=myttaddressmap&id=2119 404 (Not Found)`
but the Call should be `POST http://mydomain.de/address/ajax-map/index.php?eIDx=myttaddressmap&id=2119 404 (Not Found)` or? Clicking on "Search" or "Show more" fires the error.

The Detail-Page is showing Error
```
Call to a member function getLatitude() on null
in /app/web/typo3conf/ext/myttaddressmap/Classes/ViewHelpers/MapShowJSViewHelper.php line 109
```

The Serach-Page ist working.

- in the end i want to show on default the map with all addresses and possible to filter by zip, city and radius (seachform) is that possible?

- What is the difference between detailsPageId and singleViewUid ?

- the search only finds addresses if lat/long is set.
does this means that Google Maps Geocoding API not working?

- the search works with city only but with zip only does not working.

- is it possible to add more steps to radius or change the radius steps?

Thank you very much

**Comment by bh-teufels** [comment]
one more thing 
it only finds addresses if lat/long is set.
does this means that Google Maps Geocoding API not working?

**Comment by joachimruhs** [comment]
Hi,

detailsPageId is the PageID where the SingleView Plugin is located.

singleViewUid is the Uid if you want to show only a single location without any search... 

...

From: bh-teufels 
Sent: Friday, May 29, 2020 1:29 PM
To: joachimruhs/myttaddressmap 
Cc: Subscribed 
Subject: [joachimruhs/myttaddressmap] Errors on using map/single-view (#1)

Hello,

i placed the Plugins like in the extension manual

[2111] address

  a.. [2119] ajax map 
  b.. [2120] search (combined form and result) 
  c.. [2121] detail 
My configuration:

plugin.tx_myttaddressmap {
    settings {

    	resultPageId = 2120
    	detailsPageId = 2121
    	singleViewUid = 2121

	googleBrowserApiKey = ***
	googleServerApiKey = ***
	}
}
but if i open the Page "ajax map" i get the JS Error
POST http://mydomain.de/address/index.php?eIDx=myttaddressmap&id=2119 404 (Not Found)
but the Call should be POST http://mydomain.de/address/ajax-map/index.php?eIDx=myttaddressmap&id=2119 404 (Not Found) or? Clicking on "Search" or "Show more" fires the error.

The Detail-Page is showing Error

Call to a member function getLatitude() on null
in /app/web/typo3conf/ext/myttaddressmap/Classes/ViewHelpers/MapShowJSViewHelper.php line 109
The Serach-Page ist working.

in the end i want to show on default the map with all addresses and possible to filter by zip, city and radius (seachform) is that possible?

What is the difference between detailsPageId and singleViewUid ?

Thank you very much

**Comment by joachimruhs** [comment]
Hi,

did you have an google API account
and have inserted the required API Keys?

...

**Comment by joachimruhs** [comment]
Hi,

the singleViewUid is normally 1.

This can be used to show a map without any search and 1 is the ttaddress.uid.


Important: Did you set the storagePid in the constant editor?

...



From: bh-teufels 
Sent: Friday, May 29, 2020 1:29 PM
To: joachimruhs/myttaddressmap 
Cc: Subscribed 
Subject: [joachimruhs/myttaddressmap] Errors on using map/single-view (#1)

Hello,

i placed the Plugins like in the extension manual

[2111] address

  a.. [2119] ajax map 
  b.. [2120] search (combined form and result) 
  c.. [2121] detail 
My configuration:

plugin.tx_myttaddressmap {
    settings {

    	resultPageId = 2120
    	detailsPageId = 2121
    	singleViewUid = 2121

	googleBrowserApiKey = ***
	googleServerApiKey = ***
	}
}
but if i open the Page "ajax map" i get the JS Error
POST http://mydomain.de/address/index.php?eIDx=myttaddressmap&id=2119 404 (Not Found)
but the Call should be POST http://mydomain.de/address/ajax-map/index.php?eIDx=myttaddressmap&id=2119 404 (Not Found) or? Clicking on "Search" or "Show more" fires the error.

The Detail-Page is showing Error

Call to a member function getLatitude() on null
in /app/web/typo3conf/ext/myttaddressmap/Classes/ViewHelpers/MapShowJSViewHelper.php line 109
The Serach-Page ist working.

in the end i want to show on default the map with all addresses and possible to filter by zip, city and radius (seachform) is that possible?

What is the difference between detailsPageId and singleViewUid ?

Thank you very much

**Comment by joachimruhs** [comment]
Hi,

may be you have a Problem with the slug.
Make sure to use only a simple slug like /ajaxmap.

**Comment by bh-teufels** [comment]
Thank you for the infos

i have the required api keys for Google Maps JavaScript API and Google Maps Geocoding API 
(both the same API)

i have set the storagePID in the Plugin but will try with setting over Constants

in the Backend i can add MyTTAddressMap > Address Record but could only set name. 
is this necessary?

**Comment by joachimruhs** [comment]
Hello,

did you have activated the Google Geocoding API?
Can I get the URL to see it working?

If so, then the extension should fetch the latitude and longitude values from google,
if these values are 0.0...

...

**Comment by joachimruhs** [comment]
Look here :

https://www.joachim-ruhs.de/myttaddressmap

**Comment by joachimruhs** [comment]
This is not necessary: “in the Backend i can add MyTTAddressMap > Address Record but could only set name.”



From: bh-teufels 

Sent: Friday, May 29, 2020 3:07 PM
To: joachimruhs/myttaddressmap 
Cc: joachimruhs ; Comment 
Subject: Re: [joachimruhs/myttaddressmap] Errors on using map/single-view (#1)

Thank you for the infos

i have the required api keys for Google Maps JavaScript API and Google Maps Geocoding API
(both the same API)

i have set the storagePID in the Plugin but will try with setting over Constants

in the Backend i can add MyTTAddressMap > Address Record but could only set name.
is this necessary?

**Comment by bh-teufels** [comment]
thank you very much. 
The ajax-map seems to working now after setting the storagePid in constants.
lat/lon still necessary but that would not be a problem.

is it possible to add the radius-dropdown in the MyTTAddressMap (Map)-View?

**Comment by joachimruhs** [comment]
Hi,

the radius is set in the template AjaxSearch.html (script part).

If you do not insert a location/city and you change only the country then 
only the locations of the selected country are shown...

It is important, the the country values in tt_address match the values of the select field in the 
AjaxSearch.html.

Regards

    Joachim Ruhs

**Comment by bh-teufels** [comment]
so for radius search i have to use the search-plugin(Template) 
is it possible (in the search template) to always show the map not only on results

**Comment by joachimruhs** [comment]
Hi,

if you want to show a map without search, take the ajaxSearch.

You can insert there a city / address and you can limit the results at a time (10 or some more) – Pagination...

and in the template is written:

  // if you want manually set the search radius comment the following line and
  // set the text field tx_myttaddressmap_radius to another class, not hidden!

  $('#tx_myttaddressmap_radius').val('20000');

...

**Comment by bh-teufels** [comment]
thank you for your help i will take a closer look at the ajaxSearch and ajaxMap

**Comment by joachimruhs** [comment]
Ok,

I close this issue..

Regards

    Joachim Ruhs

**Comment by joachimruhs** [comment]
Can I get the URL?

**Comment by bh-teufels** [comment]
It is on jp based access only i have to make a public accessible

Holen Sie sich Outlook für iOS<https://aka.ms/o0ukef>
________________________________
Von: joachimruhs <notifications@github.com>
Gesendet: Thursday, July 30, 2020 5:35:27 PM
An: joachimruhs/myttaddressmap <myttaddressmap@noreply.github.com>
Cc: Bastian Holzem <b.holzem@teufels.com>; Author <author@noreply.github.com>
Betreff: Re: [joachimruhs/myttaddressmap] Errors on using map/single-view (#1)


Can I get the URL?

**Comment by bh-teufels** [comment]
the url for default language (german) (working) ist 
https://staging.hlg.steigtechnik.teufels-werk.de/haendlersuche
the url for translation (en) is 
https://staging.hlg.steigtechnik.teufels-werk.de/en/retailer-search

the user and password for access is myttaddressmap

Thank you
