### ISSUE TITLE
Problem with templateRootPaths

### ISSUE THREAD

**Issue by theandy** [joachimruhs/myttaddressmap#10]
Hi. 

When I set the `plugin.tx_myttaddressmap.view.templateRootPath` in constants, the extension doesn't work if the file `Address/AjaxLocationListInfoWindow.html` is missing in this folder. I think, the extension usually should search for this file in fallback path `templateRootPaths.0`? If I don't copy `AjaxLocationListInfoWindow.html` to my folder, the console in Chrome DevTools gives me an error (500 (Internal Server Error).

Best regards
Andy

**Comment by joachimruhs** [comment]
Hi,
thats because it is called via Ajax. Just copy all files from templates...

Regards
