### ISSUE TITLE
Pins not "loaded" on translated Page (404 for  domain.de/en/index.php?eIDx=myttaddressmap&id=2208)

### ISSUE THREAD

**Issue by bh-teufels** [joachimruhs/myttaddressmap#2]
Hello on my Translated "Map"-Page the pins ans search not working 
i get error  `POST https://mydomain.de/en/index.php?eIDx=myttaddressmap&id=2208 404`
maybe same as issue #1 ?

Using MyTTAddressMap (Map) Plugin

**Comment by joachimruhs** [comment]
Hi,
try to use a leading "/" in template AjaxSearch.html
var ajaxRequestUrl = "/index.php?eIDx=myttaddressmap&id

Did this help?

**Comment by bh-teufels** [comment]
Thank you i will Texte this tomorrow

Holen Sie sich Outlook für iOS<https://aka.ms/o0ukef>
________________________________
Von: joachimruhs <notifications@github.com>
Gesendet: Thursday, July 30, 2020 6:56:29 PM
An: joachimruhs/myttaddressmap <myttaddressmap@noreply.github.com>
Cc: Bastian Holzem <b.holzem@teufels.com>; Author <author@noreply.github.com>
Betreff: Re: [joachimruhs/myttaddressmap] Pins not "loaded" on translated Page (404 for domain.de/en/index.php?eIDx=myttaddressmap&id=2208) (#2)


Hi,
try to use a leading "/" in template AjaxSearch.html
var ajaxRequestUrl = "/index.php?eIDx=myttaddressmap&id

Did this help?

**Comment by joachimruhs** [comment]
See here: https://www.web-services-ruhs.de/en/myttaddress-en
works like expected!

**Comment by bh-teufels** [comment]
using leading "/" in  template AjaxSearch.html `var ajaxRequestUrl = "/index.php?eIDx=myttaddressmap&id` fixed the problem thank you very much. 

But the Labels from template AjaxLocationList.html are not translated all are integrated in translation files
`<f:translate key="LLL:EXT:hive_thm_custom/Resources/Private/Language/translation.myttadressmap.xlf:myttaddressmap.phone" />`

**Comment by joachimruhs** [comment]
Hi,
good. 
I have published a new release which has a better handling of own icons... when used with localization.

Ok, closing the issue...

**Comment by bh-teufels** [comment]
okay thank you,.
when will it come to TER? 
the Version there is still 1.0.8


i'm not sure if this fix the problem but i could find the reason:

in the AjaxSearch.html template the Language has to be add to the ajaxRequestUrl 
`var ajaxRequestUrl = "/index.php?eIDx=myttaddressmap&id=" + id + "&L=" + languageUID`

therefore the languageUID has to assigned to the template

**Comment by bh-teufels** [comment]
i am now on Version 1.1.0 but the translation nor working
using AjaxSearch.html and AjaxLocationList.html

if i put for example the languageUID "hard" into the ajaxRequestURL var ajaxRequestUrl = "/index.php?eIDx=myttaddressmap&id=" + id + "&L=1" i get the translation (for Language Uid 1)
