### ISSUE TITLE
Loading the Google Maps JavaScript API without a callback is not supported

### ISSUE THREAD

**Issue by bh-teufels** [joachimruhs/myttaddressmap#20]
Loading the Google Maps JavaScript API without a callback is not supported: https://developers.google.com/maps/documentation/javascript/url-params#required_parameters

it ist needed to adjust a callback function with the API Key.
What is the function that should be specified here?

**Comment by joachimruhs** [comment]
Hi,

you can try to use the function load(). 
But I use it without callback and it still runs.

Regards

**Comment by bh-teufels** [comment]
with load i get error `load is not a function`

my API Key:
plugin.tx_myttaddressmap.settings.googleBrowserApiKey = AbcdEfGHijkl12345_a1b2c3d4e5&callback=load
plugin.tx_myttaddressmap.settings.googleServerApiKey =AbcdEfGHijkl12345_a1b2c3d4e5&callback=load

**Comment by joachimruhs** [comment]
Hi,
just remove the callback func.

Do You load the jQuery on top of th epage?

**Comment by bh-teufels** [comment]
yes jQuery is loaded on top

if i remove the callback function i get the error
`Loading the Google Maps JavaScript API without a callback is not supported: https://developers.google.com/maps/documentation/javascript/url-params#required_parameters`

**Comment by joachimruhs** [comment]
Hi,
in the template you can create a dummy function and then try it as callback...
What happens then.

Here I work still without callback!
https://www.web-services-ruhs.de/myttaddress/ajaxsearch

**Comment by bh-teufels** [comment]
still get error but seems to be due to the API key and the configuration in the Google account

**Comment by joachimruhs** [comment]
Just delete the api  keys in the constant editor of TYPO3 myttaddressmap...
The map should be still loaded but in developer mode.

Have you got the keys from Google?

**Comment by bh-teufels** [comment]
It was probably due to a domain restriction with the API key. Does the API call use a separate domain from the domain where the plugin (MAP) is placed? 
If i remove the domain restriction from the API it is working. But I would like to keep that.

**Comment by joachimruhs** [comment]
The keys you have look to me not be from google.
But first do not set any restrictions and when it works you can restrict the browser key to your domain and the server key to your IP.

**Comment by joachimruhs** [comment]
Hi,
the server API key is used to geolocate the address. Therfor you should use another key and keep that secret and restrict this key to your server IP address.

**Comment by bh-teufels** [comment]
yes the keys are from Google but the keys i put here are not the correct ones.

**Comment by bh-teufels** [comment]
thanks very much
with Browser API (domain restricted) & Server API (IP restricted) it's working
