### ISSUE TITLE
TypeError: AddressController

### ISSUE THREAD

**Issue by peter-neumann-dev** [joachimruhs/myttaddressmap#21]
Hi, we have a problem with a v10 installation where we want to use the existing addresses to use them in the map. Unfortunately a TypeError happens when we would like to use the existing addresses. If I create a new folder with new addresses, it works.

My guess is that it is an issue with the existing data and maybe a faulty record or something. Since I am more FE focused, maybe someone can give me a hint what I need to search for in the existing addresses.  

<img width="1216" alt="Peter Neumann 2023-08-08 at 19 51 07@2x" src="https://github.com/joachimruhs/myttaddressmap/assets/75690659/e03d882e-d521-4b22-990c-8a079772d994">

```
Argument 1 passed to WSR\Myttaddressmap\Controller\AddressController::buildTree() must be of the type array, null given, called in /var/www/html/public/typo3conf/ext/myttaddressmap/Classes/Controller/AddressController.php on line 390
```

**Comment by joachimruhs** [comment]
Hi,
have you inserted some sys_categories?

**Comment by peter-neumann-dev** [comment]
Ah, yeah, this was the problem! 🤦‍♂️ Thank you! 😄
In my test folder there were some categories. Why is at least one needed?

**Comment by joachimruhs** [comment]
The search needs categories for the selection.
This is in the docu:

Then insert at least one sys_category in the page Data. Now insert some tt_address data records and assign them to sys_categories.

Regards

**Comment by peter-neumann-dev** [comment]
I read about this. Now I do not understand even when I add a category to the folder but to none of the tt_address records why it is working like that. So my search is working only with one category even when it is not used anywhere. 🤔 Sorry, maybe I am blocked in my head somewhere 😄
