### ISSUE TITLE
TypoScript file extensions outdated

### ISSUE THREAD

**Issue by peter-neumann-dev** [joachimruhs/myttaddressmap#23]
We had a problem during the upgrade that loading the TypoScript files with `.ts` from this extension is not possible with the `@import` syntax.

Maybe to keep old includes working, it would help to create additional new files ending with the correct `.typoscript` ending and importing them into the old legacy `.ts` files.

For example, news is doing that: https://github.com/georgringer/news/blob/main/Configuration/TypoScript/setup.txt

**Comment by peter-neumann-dev** [comment]
The related core changelog entry: https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/10.3/Important-89720-OnlyTypoScriptFilesLoadedOnDirectoryImport.html#important-89720-only-typoscript-files-loaded-on-directory-import

**Comment by joachimruhs** [comment]
Hi,
which TYPO3 version you have?

**Comment by peter-neumann-dev** [comment]
TYPO3 v12

We are loading all Extensions like this to avoid storing those things in the database:
`@import 'EXT:myttaddressmap/Configuration/TypoScript/setup.ts'`

**Comment by peter-neumann-dev** [comment]
It will only be visible in the TypoScript Module:
![peter-neumann-dev-20240626-151414](https://github.com/joachimruhs/myttaddressmap/assets/75690659/fa050333-0ab9-4c4a-88b2-2bbbe93fc8b1)
Here, we have included the `setup.ts` like mentioned

**Comment by joachimruhs** [comment]
Hi,
will be done in next version of myttaddressmap.
