### ISSUE TITLE
Failed loading of coordinates

### ISSUE THREAD

**Issue by marcusthiele** [joachimruhs/myttaddressmap#25]
I have a TYPO3 v12, tt_address v8.1 and myttaddressmap v2.2.6.
For some reason, after I search for a contact, I get the following error.
`(1/1) #1476107295 TYPO3\CMS\Core\Error\Exception
PHP Warning: Undefined array key "zip" in /var/www/html/vendor/wsr/myttaddressmap/Classes/Controller/AddressController.php line 591`

The coordinates are not loaded and longitude and latitude fields remain empty. When I check the BE and click the mapicon the marker is set correctly.

**Comment by joachimruhs** [comment]
Hi,
if you set the preset to live the warning is only written to logs.
The error is here: change zip to zipcode then it works line 582ff.

`	public function geocode($theAddress) {
		//for urlencoding
		$vars = array (
			'zipcode',`

**Comment by marcusthiele** [comment]
Hi, yes I did.
Right now it seems I have too much items to be loaded (163).
The zip error does not appear anymore but I'm not getting the map either. I'll try to put the environment to LIVE and try again

Nachricht von joachimruhs ***@***.***> am 17. Juli 2024, 09:14 +0200:

**Comment by joachimruhs** [comment]
Hi,
did you have loaded jQuery on top of the page?
Can you  give me the URL?
Is the problem solved?
