### ISSUE TITLE
window.history.back() not working with POST method of form

### ISSUE THREAD

**Issue by marcusthiele** [joachimruhs/myttaddressmap#26]
History Back function on SingleView template is not working with POST method of SearchForm and results in the error that the browser wants to reload the page and send the form again.

**Comment by joachimruhs** [comment]
Yes, that is correct. After reloading you get the results again.
See https://wsr12.web-services-ruhs.de/extensions/searchform
and search for rust.

Or, if you want to go to the SerachForm you can use this in SingleView.html
`<div onclick="window.history.go(-2);">Zurück</div>`



Regards
Joachim Ruhs
