### ISSUE TITLE
API Key Error: Geocoding Error: REQUEST_DENIED

### ISSUE THREAD

**Issue by bh-teufels** [joachimruhs/myttaddressmap#29]
If I restrict the Google Maps API key to the domain (even when using Wildcard) or IP, I get the error: Geocoding Error: REQUEST_DENIED

If I set the application restrictions to "Not available", it works.
Is there another external domain to which a connection must be established?

**Comment by joachimruhs** [comment]
Hi,
there are 2 keys.
I think you mean the server API key. This key should be restricted to the IP address of the server.
...

**Comment by bh-teufels** [comment]
sorry for the question but how do the APIs have to be divided up?

Which APIs are needed for the browser API and which for the server API
- JavaScript API
- Geocoding API
- Places API

**Comment by bh-teufels** [comment]
and in the documentation it says "restrict the browser key with http url and the server key with ip address of the webserver to prevent illegal use of the keys."

**Comment by joachimruhs** [comment]
Hi,
the browser key is visible in the html source code.
The server key is only needed to geocode a location. 

I have Geocding API
and Maps Javascript API.

**Comment by bh-teufels** [comment]
thank you
I can't search for addresses without using the places API
but with places it all works fine
