### ISSUE TITLE
Crowdin integration fails

### ISSUE THREAD

**Issue by prathers** [joachimruhs/myttaddressmap#30]
You have an unconfigured branch on the Crowdin project:https://crowdin.com/project/typo3-extension-myttaddressmap/integrations/system/github

In order to reenable sync, please double-click on the necessary branch to create a configuration.

More help: https://crowdin.com/project/typo3-extension-myttaddressmap/integrations/system/github

**Comment by joachimruhs** [comment]
Hi,
I hope I have fixed that...

**Comment by prathers** [comment]
Thanks a million. It works again
