### ISSUE TITLE
Show all translated categories on location not only the category of the (sys)language

### ISSUE THREAD

**Issue by bh-teufels** [joachimruhs/myttaddressmap#4]
the category-list output `{location.categories}` on AjaxLocationList.html contains all assigned and translated categories.

What ist the Output:
_assigned_categoryA_inEnglish, assigned_categoryA_inGerman, assigned_categoryA_inSpain, assigned_categoryB_inEnglish, assigned_categoryB_inGerman, assigned_categoryB_inSpain__ 

How it should be:
on SysLanguage = 0 = EN
_assigned_categoryA_inEnglish, assigned_categoryB_inEnglish_

on SysLanguage = 1 = DE
_assigned_categoryA_inGerman, assigned_categoryB_inGerman_

on SysLanguage = 2 = ES
_assigned_categoryA_inSpain, assigned_categoryB_inSpain_

**Comment by joachimruhs** [comment]
The localized category selection is not implemented yet. May be in a future version.
