### ISSUE TITLE
Doesn't work with own Templates

### ISSUE THREAD

**Issue by taunusweb** [joachimruhs/myttaddressmap#5]
When I try to use my own Templates (even if they are not changed) I get no output, it works well, when I don't change the Template Path. Any Idea? Here my examples, no difference except the template Path:
https://phv-upgrade.taunus-webservices.de/ueber-phv/unsere-standorte/search-1 (not working)
https://phv-upgrade.taunus-webservices.de/ueber-phv/unsere-standorte/search (working)
Thanks Uli

**Comment by taunusweb** [comment]
Ahh, when I set my own Layout and Partial Path to, it works like expected... Is that right?

**Comment by joachimruhs** [comment]
You have to set the paths in the constant editor not the setup.ts!

**Comment by taunusweb** [comment]
Yes, I've used the constant editor.

**Comment by joachimruhs** [comment]
you can try the constant enableMarkerClusterer = 1

**Comment by joachimruhs** [comment]
Works now fine?

**Comment by taunusweb** [comment]
It's fine for me now. Any hints for disable the scrollwheel zoom? Or to use: gestureHandling: "cooperative",?

**Comment by joachimruhs** [comment]
The map is created with the MapJSViewHelper.
There you can see
             myOptions = {
              zoom: zoom1,
              center: latlng,
        //		      mapTypeId: google.maps.MapTypeId.ROADMAP,
              scaleControl: true,
              zoomControl: true,
              zoomControlOptions: {
                    position: google.maps.ControlPosition.LEFT_TOP
                },
...

Hope this  help a bit

**Comment by joachimruhs** [comment]
I have uploaded a new MapJSViewhelp with gestureHandling and disabled ScrollWheel...

**Comment by taunusweb** [comment]
Works like a charme, thanks a lot!
