### ISSUE TITLE
Geocode stoppt working

### ISSUE THREAD

**Issue by fazzyx** [joachimruhs/myttaddressmap#6]
TYPO3 Version current 9 / 10 LTS
myttaddressmap Version 1.3.6
MySQL Version 5.7.x

tt_address entries with empty lat / long fields got no more coordinates after search / call in the frontend.
A debug get me to an issue with the sql query.
The database fields contain NULL value and the database query which is looking for entries with NULL is using "equal" NULL (=NULL).
After I changed it to "isNull" it works again.

Changed 
`$queryBuilder->expr()->eq('latitude', $queryBuilder->createNamedParameter(NULL, \PDO::PARAM_NULL)),`
`$queryBuilder->expr()->eq('longitude', $queryBuilder->createNamedParameter(NULL, \PDO::PARAM_NULL))`
To
`$queryBuilder->expr()->isNull('latitude'),`
`$queryBuilder->expr()->isNull('longitude')`

I'm not sure if the createNamedParameter() is needed here, cause there is no user input

**Comment by joachimruhs** [comment]
Hello,
thx for reporting.

createNamedParameter should be used everywhere...

						$queryBuilder->expr()->isNull('latitude', $queryBuilder->createNamedParameter(NULL, \PDO::PARAM_NULL)),
						$queryBuilder->expr()->isNull('longitude', $queryBuilder->createNamedParameter(NULL, \PDO::PARAM_NULL))

Will be inserted in the next version of the extension...

Regards

**Comment by fazzyx** [comment]
Thank you for the fast reaction!
