### ISSUE TITLE
Address getName() failed on missing object

### ISSUE THREAD

**Issue by fazzyx** [joachimruhs/myttaddressmap#7]
TYPO3 Version current 9 / 10 LTS
myttaddressmap Version 1.3.6
MySQL Version 5.7.x

Related to AddressController function updateLatLon() (524)
If latLon stat is not 'OK' the call $address->getName() for the output message cannot work because of object is missing.

There should also be an object available as it is in "if"
$address = $this->addressRepository->findByUid($theAddress['uid']);

**Comment by joachimruhs** [comment]
Fixed...

**Comment by fazzyx** [comment]
Thank you!
